package com.inb.spendly.ui.theme

import com.inb.spendly.R

object CategoryIcons {
    val icons = listOf(
        R.drawable.baseline_card_travel_24,
        R.drawable.baseline_event_24,
        R.drawable.baseline_games_24,
        R.drawable.baseline_hotel_24,
        R.drawable.baseline_music_note_24,
        R.drawable.baseline_smartphone_24,
        R.drawable.outline_account_balance_wallet_24,
        R.drawable.outline_airplane_ticket_24,
        R.drawable.outline_attach_money_24,
        R.drawable.outline_book_3_24,
        R.drawable.outline_build_24,
        R.drawable.outline_checkroom_24,
        R.drawable.outline_cleaning_24,
        R.drawable.outline_coffee_24,
        R.drawable.outline_computer_24,
        R.drawable.outline_credit_card_24,
        R.drawable.outline_currency_exchange_24,
        R.drawable.outline_devices_24,
        R.drawable.outline_diamond_24,
        R.drawable.outline_digital_wellbeing_24,
        R.drawable.outline_directions_bus_24,
        R.drawable.outline_directions_car_24,
        R.drawable.outline_face_24,
        R.drawable.outline_family_group_24,
        R.drawable.outline_fastfood_24,
        R.drawable.outline_favorite_24,
        R.drawable.outline_featured_seasonal_and_gifts_24,
        R.drawable.outline_fitness_center_24,
        R.drawable.outline_flight_24,
        R.drawable.outline_health_and_safety_24,
        R.drawable.outline_home_24,
        R.drawable.outline_image_24,
        R.drawable.outline_local_gas_station_24,
        R.drawable.outline_local_hospital_24,
        R.drawable.outline_local_pizza_24,
        R.drawable.outline_local_taxi_24,
        R.drawable.outline_medication_24,
        R.drawable.outline_movie_24,
        R.drawable.outline_payments_24,
        R.drawable.outline_pet_supplies_24,
        R.drawable.outline_question_mark_24,
        R.drawable.outline_restaurant_24,
        R.drawable.outline_school_24,
        R.drawable.outline_self_care_24,
        R.drawable.outline_shopping_bag_24,
        R.drawable.outline_shopping_cart_24,
        R.drawable.outline_spa_24,
        R.drawable.outline_sports_esports_24,
        R.drawable.outline_stadium_24,
        R.drawable.outline_subscriptions_24,
        R.drawable.outline_tools_power_drill_24,
        R.drawable.outline_train_24,
        R.drawable.outline_wine_bar_24,
        R.drawable.outline_work_24
    )
}